# Generated by Django 3.1.6 on 2021-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('domain', 'slug'), name='Domain-Slug constraint'),
        ),
    ]
