# Generated by Django 3.1.6 on 2021-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_auto_20210630_0030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='link',
            name='Domain-Slug constraint',
        ),
        migrations.RemoveField(
            model_name='link',
            name='domain',
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Slug'),
        ),
    ]
