# Generated by Django 3.1.6 on 2021-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_auto_20210702_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Slug'),
        ),
    ]
