# Generated by Django 3.1.6 on 2021-07-10 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0004_auto_20210702_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Name of domain'),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Slug'),
        ),
    ]
