# Generated by Django 3.1.6 on 2022-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0007_auto_20220103_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securelink',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Slug'),
        ),
    ]
